### ISSUE TITLE
Exception caught: Mysql::Error: query: not connected

### ISSUE THREAD

**Issue by amacgregor** [rubyrep/rubyrep#55]
Hi,

I keep the following error when testing rubyrep

rubyrep --verbose scan -c testconf                                                                                                                 in ~
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/table_spec_resolver.rb:91: warning: encoding option is ignored - U
Exception caught: Mysql::Error: query: not connected: SHOW TABLES 
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in`block in execute'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.2.5/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in`execute'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/mysql_adapter.rb:314:in `execute_and_free'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:381:in`tables'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/table_spec_resolver.rb:14:in `tables'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/table_spec_resolver.rb:91:in`block in expand_table_specs'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/table_spec_resolver.rb:83:in `each'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/table_spec_resolver.rb:83:in`expand_table_specs'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/table_spec_resolver.rb:58:in `resolve'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/session.rb:45:in`manual_primary_keys'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/session.rb:215:in `connect_database'
/home/mbertulli/.rvm/gems/ruby-1.9.2-head/gems/rubyrep-1.2.0/lib/rubyrep/session.rb:179:in`block in refresh_database_connection'

**Comment by bradrushworth** [comment]
See #61 for a resolution...
