### ISSUE TITLE
Exception caught: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by vadirajks** [rubyrep/rubyrep#64]
Hi Team,

Its almost 3 days now and nothing is moving from this below error. Please can anyone help me to fix this .

[root@NOC1 ~]# rubyrep --verbose  scan -c /tmp/myrubyrep.conf Exception caught: no implicit conversion of String into Integer
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql_adapter.rb:456:in `real_connect'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql_adapter.rb:456:in `connect'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql_adapter.rb:108:in `initialize'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql_adapter.rb:36:in `new'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql_adapter.rb:36:in `mysql_connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/lib64/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/lib64/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/connection_extenders/connection_extenders.rb:66:in `db_connect_without_cache'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/connection_extenders/connection_extenders.rb:143:in `db_connect'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/proxy_connection.rb:230:in `initialize'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/database_proxy.rb:29:in `new'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/database_proxy.rb:29:in `create_session'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/session.rb:213:in `connect_database'
/usr/lib64/ruby/gems/2.3.0/gems/rubyrep-1.2.0/lib/rubyrep/session.rb:179:in `block in refresh_database_connection'
[root@NOC1 ~]# 

i wanted to setup replication from mysql to postgresql DB.

[root@NOC1 ~]# cat /tmp/myrubyrep.conf
RR::Initializer::run do |config|
  config.left = {
    :adapter  => 'mysql', # or 'postgresql'
    :database => 'reporting',
    :username => 'abc',
    :password => 'abc',
    :host     => '192.168.0.9',
    :port     => '3306'
  }
  config.right = {
    :adapter  => 'postgresql',
    :database => 'reporting',
    :username => 'postgres',
    :password => 'abc',
    :host     => '192.168.0.44',
    :port     => '5439',
    :schema_search_path => 'teststagingdb' 
  }
  config.options[:sync_conflict_handling] = :right_wins
  config.options[:replication_conflict_handling] = :right_wins
  config.include_tables /./ # regexp matching all tables in the database
  config.include_tables 'schema_migrations', :key => 'version'
end
[root@NOC1 ~]# 

Thanks,
Vadiraj

**Comment by vadirajks** [comment]
Hi Team,

I am struggling to figure out from last few days and nothing working out . I need to setup replication between mysql to postgresql very badly. Please can anyone help me here.

at least please let me know what are the dependence so that i can following and try to workout accordingly.

1>postgresql version.
2>mysql version.
3>ruby version.
4> jruby version ( do i need to use ruby or jruby....is there anything dependence tools based on this)
5>rubygems version.
6>rubygem-activesupport  version.
7>rubygem-activerecord  version.
8>rubygem-activemodel  version.
9>rubygem-activerecord-mysql2-adapter
10>any specific version for below
gem install mysql2
gem install pg

and let me know if anything i am missing.

It looks like one of the great tool but unfortunately i am unable to make this working .

any Linux version is okay for me (RHEL,centos...etc)
 
Any help will be greatly appreciated!? 

Thankyou,
Vadiraj

**Comment by ccbamatx** [comment]
I used:
:adapter => 'mysql2'
