### ISSUE TITLE
getting exception undefined method `[]' for nil:NilClass for replication while sync/scan works

### ISSUE THREAD

**Issue by aero-108** [rubyrep/rubyrep#69]
Hi,
anyone can point why sync/scan works without any single problem, but replicate option throws exception:

```
Verifying RubyRep tables
Checking for and removing rubyrep triggers from unconfigured tables
Verifying rubyrep triggers of configured tables
Exception caught: undefined method `[]' for nil:NilClass
/xxxxx/r/lib/rubyrep/replication_extenders/postgresql_replication.rb:183:in `block in update_sequences'
org/jruby/RubyHash.java:1343:in `each'
/xxxxx/r/lib/rubyrep/replication_extenders/postgresql_replication.rb:177:in `update_sequences'
/xxxxx/r/lib/rubyrep/replication_initializer.rb:83:in `block in ensure_sequence_setup'
org/jruby/RubyArray.java:1734:in `each'
/xxxxx/r/lib/rubyrep/replication_initializer.rb:79:in `ensure_sequence_setup'
/xxxxx/r/lib/rubyrep/replication_initializer.rb:298:in `block in prepare_replication'
org/jruby/RubyArray.java:1734:in `each'
/xxxxx/r/lib/rubyrep/replication_initializer.rb:293:in `prepare_replication'
/xxxxx/r/lib/rubyrep/replication_runner.rb:114:in `prepare_replication'
/xxxxx/r/lib/rubyrep/replication_runner.rb:142:in `execute'
/xxxxx/r/lib/rubyrep/replication_runner.rb:168:in `run'
/xxxxx/r/lib/rubyrep/command_runner.rb:102:in `run'
./bin/rubyrep:7:in `<main>'
```

Any help appreciated.

**Comment by alehmann** [comment]
rubyrep assumes that the database schemas in left and right database are in sync.
If they are not, this often results in (the ruby equivalent of) null-pointer exceptions. (Todo for the future would be to implement better checks so that such situations result in more meaningful error messages.)

Here the exception is triggered during sequence setup. I suggest you check and confirm that all replicated tables have the same sequences in left and right database. Specifically the sequences must exist and must have the same names.
